### ISSUE TITLE
Improve Docker images structure

### ISSUE THREAD

**Issue by etiennetremel** [skycoin/docker-img#4]
I kind of feel unconfortable seeing a dedicated Docker repository for an entire project, I guess there is a good reason behind this idea but here are some suggestion that could help improve the Skycoin infra:

1. Docker images should be setup in each repository, one Dockerfile per project
2. make use of multi-staged build: one to compile with GoLang, another to host the binary
3. use alpine or scratch image to slim down the image, currently the image it 800Mb, if using the scratch image we can slim it down to ~5-20Mb
4. use DockerHub for automated build

If you think that would work or have other suggestion let me know, I would love to work on it!

**Comment by gz-c** [comment]
1. How are different dockerfiles/configurations handled, within the same repo?
2. ok
3. ok
4. ok but need more details

**Comment by etiennetremel** [comment]
1. By moving the Dockerfile from this repository to the skycoin/skycoin repo and create an automated build, the container can be automatically build without having to use an external CI/CD system. Also, you can keep track of image versioning by using tags or branch name. Here are the repository that I'm thinking about creating a Dockerfile:
- https://github.com/skycoin/bbs
- https://github.com/skycoin/cxo
- https://github.com/skycoin/skycoin
- https://github.com/skycoin/skywire

Maybe there is others?

2 & 3, I issued a PR for this repo; see https://github.com/skycoin/docker-img/pull/5; then if you decide on point 1, I can do the same for the repositories listed above.

4. DockerHub automated build is a Github webhook which trigger Docker build, this is free and if you create an official DOckerHub account, you can set this up following this documentation: https://docs.docker.com/docker-hub/builds/

**Comment by gz-c** [comment]
https://github.com/skycoin/teller is another

**Comment by gz-c** [comment]
Added automated builds for bbs, cxo, skycoin, skywire and teller to docker hub under the "skycoin" organization

**Comment by gz-c** [comment]
<img width="1270" alt="screen shot 2017-12-31 at 3 52 52 pm" src="https://user-images.githubusercontent.com/26845312/34460184-b7f97f14-ee42-11e7-8da4-11ea34de9789.png">

**Comment by etiennetremel** [comment]
@gz-c almost there, for BBS we need to upgrade CXO to the latest version which had a fix about CGO cross compiling and home directory usage via the `os/user` package.
